In [1]:
import nltk
import numpy as np 

import re   
from nltk.corpus import stopwords 

In [2]:
import pandas as pd

In [3]:
data=pd.read_csv("finalizedtweets.csv")

In [4]:
data.shape

(13613, 2)

In [5]:
data.head()


airline_sentiment                                               text
0           neutral                               What @dhepburn said.
1          positive   plus you've added commercials to the experien...
2           neutral   I didn't today... Must mean I need to take an...
3          negative   it's really aggressive to blast obnoxious "en...
4          negative           and it's a really big bad thing about it

In [6]:
data.describe()

airline_sentiment                  text
count              13613                 13613
unique                 3                 13583
top             negative   Thank you, you too!
freq                8488                     2

In [7]:
data["airline_sentiment"].value_counts()

negative    8488
neutral     2941
positive    2184
Name: airline_sentiment, dtype: int64

In [8]:
data["airline_sentiment"].replace({"positive":1,"negative":0,"neutral":2},inplace=True)

In [9]:
data.head()

airline_sentiment                                               text
0                  2                               What @dhepburn said.
1                  1   plus you've added commercials to the experien...
2                  2   I didn't today... Must mean I need to take an...
3                  0   it's really aggressive to blast obnoxious "en...
4                  0           and it's a really big bad thing about it

In [10]:
x=data.drop(["airline_sentiment"],axis=1)
y=data["airline_sentiment"]

In [11]:
X=[]
for i in range(len(x)):
    s=data["text"][i]
    X.append(s.lower())

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer  
tfidfconverter = TfidfVectorizer(max_features=2000, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))  
X = tfidfconverter.fit_transform(X).toarray()

In [13]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=56,stratify=y)


In [236]:
from sklearn.ensemble import RandomForestClassifier
text_classifier = RandomForestClassifier(n_estimators=100,min_samples_leaf=3,n_jobs=1)
text_classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=3, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [237]:
predictions = text_classifier.predict(X_test)
predictions_train=text_classifier.predict(X_train)

In [238]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
 
print(confusion_matrix(y_test,predictions))  
print(classification_report(y_test,predictions))  
print(accuracy_score(y_test, predictions))

[[1969   52  102]
 [ 212  289   45]
 [ 396   55  284]]
              precision    recall  f1-score   support

           0       0.76      0.93      0.84      2123
           1       0.73      0.53      0.61       546
           2       0.66      0.39      0.49       735

   micro avg       0.75      0.75      0.75      3404
   macro avg       0.72      0.61      0.65      3404
weighted avg       0.74      0.75      0.73      3404

0.7467685076380729


In [239]:
print(confusion_matrix(y_train,predictions_train))  
print(classification_report(y_train,predictions_train))  
print(accuracy_score(y_train, predictions_train))

[[6114  109  142]
 [ 461 1019  158]
 [ 798  170 1238]]
              precision    recall  f1-score   support

           0       0.83      0.96      0.89      6365
           1       0.79      0.62      0.69      1638
           2       0.80      0.56      0.66      2206

   micro avg       0.82      0.82      0.82     10209
   macro avg       0.81      0.71      0.75     10209
weighted avg       0.82      0.82      0.81     10209

0.8199627779410325


In [221]:
from sklearn import svm
classifier_linear = svm.SVC(kernel='linear',random_state=56)
classifier_linear.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=56,
  shrinking=True, tol=0.001, verbose=False)

In [222]:
prediction_linear = classifier_linear.predict(X_test)
prediction_linear_train = classifier_linear.predict(X_train)


In [223]:
print(confusion_matrix(y_train,prediction_linear_train))   
print(classification_report(y_train,prediction_linear_train))  
print(accuracy_score(y_train,prediction_linear_train))

[[6088   73  204]
 [ 279 1204  155]
 [ 735  110 1361]]
              precision    recall  f1-score   support

           0       0.86      0.96      0.90      6365
           1       0.87      0.74      0.80      1638
           2       0.79      0.62      0.69      2206

   micro avg       0.85      0.85      0.85     10209
   macro avg       0.84      0.77      0.80     10209
weighted avg       0.84      0.85      0.84     10209

0.8475854638064453


In [224]:
print(confusion_matrix(y_test,prediction_linear))   
print(classification_report(y_test,prediction_linear))  
print(accuracy_score(y_test,prediction_linear))

[[1945   53  125]
 [ 152  325   69]
 [ 336   57  342]]
              precision    recall  f1-score   support

           0       0.80      0.92      0.85      2123
           1       0.75      0.60      0.66       546
           2       0.64      0.47      0.54       735

   micro avg       0.77      0.77      0.77      3404
   macro avg       0.73      0.66      0.68      3404
weighted avg       0.76      0.77      0.75      3404

0.7673325499412456


In [53]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x_scaled=scaler.fit_transform(X)

In [54]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(x_scaled,y,random_state=56,stratify=y)

In [55]:
from sklearn.neighbors import KNeighborsClassifier as KNN

In [56]:
clf=KNN(n_neighbors=10)
clf.fit(train_x,train_y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=10, p=2,
           weights='uniform')

In [57]:
test_predict=clf.predict(test_x)

In [58]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
k=accuracy_score(test_y,test_predict)

In [59]:
k

0.4145123384253819

In [60]:
from sklearn.naive_bayes import GaussianNB

In [61]:
model=GaussianNB()

In [62]:
model.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [63]:
test_predict=model.predict(X_test)

In [64]:
accuracy_score(y_test,test_predict)

0.40569917743830786

In [65]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [66]:
model1=LogisticRegression()

In [67]:
model1.fit(X_train,y_train)

C:\Users\Kartik\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Kartik\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [68]:
test_predict1=model1.predict(X_test)
train_predict1=model1.predict(X_train)

In [70]:
accuracy_score(y_train,train_predict1)

0.8167303359780586

In [71]:
accuracy_score(y_test,test_predict1)


0.7685076380728555

In [215]:
model2=DecisionTreeClassifier(min_samples_leaf=3,max_leaf_nodes=3)

In [216]:
model2.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=3, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=3,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [217]:
test_predict2=model2.predict(X_test)

In [218]:
accuracy_score(y_test,test_predict2)

0.6621621621621622

In [76]:
#naive base classifier using nltk
from sklearn.naive_bayes import MultinomialNB 

In [77]:
model_NB=MultinomialNB()

In [78]:
model_NB.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [80]:

predict=model_NB.predict(X_test)

In [79]:
predict_train=model_NB.predict(X_train)

In [81]:
accuracy_score(predict,y_test)

0.7397179788484136

In [82]:
accuracy_score(predict_train,y_train)

0.7752963071799392

In [242]:
from statistics import mode
final_pred=np.array([])
for i in range(0,len(X_test)):
    try:
        m=mode([test_predict1[i],prediction_linear[i],predictions[i],predict[i]])
    except:
        m=test_predict1[i]
    final_pred=np.append(final_pred,m)

In [243]:
accuracy_score(y_test,final_pred)

0.7690951821386603